export const works = [
  {
    id: 1,
    category: 'Instaglam oparation / Influencer',
    content: 'We oparate thair company Instagram',
    url: 'https://www.instagram.com/naturetopcambodia?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==',
    img: '/img/natureTopCambodia.jpg',
    tag: ['SNS', 'Influencer'],
  },
  {
    id: 2,
    category: 'Video product/ Influencer',
    content: 'We produced a video using influencers in preparation for the opening of the popular Korean E-mart in Cambodia.',
    url: 'https://www.instagram.com/p/C8elQIdJd3N/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==',
    img: '/img/emart.jpg',
    tag: ['SNS', 'Influencer', 'Video'],
  },
  {
    id: 3,
    category: 'Video production',
    content: 'We created a promotional video introducing the store. ',
    url: 'https://www.instagram.com/reel/C521aPbraO2/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==',
    img: '/img/beautyJapan.jpg',
    tag: ['Influencer', 'Video'],
  },
  {
    id: 4,
    category: '',
    content: 'Coming soon',
    url: '',
    img: '/img/comingSoon.jpg',
    tag: [],
  },
  {
    id: 5,
    category: '',
    content: 'Coming soon',
    url: '',
    img: '/img/comingSoon.jpg',
    tag: [],
  },
]
